ZSU_PROD/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('api/',include('mainapp.api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/api/urls.py
from django.urls import path\

from .views import TestApiView

urlpatterns = [
    path('test-api/', TestApiView.as_view(), name='test')
]

user/urls.py
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path("", views.index, name="index"),
    path('login/', views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

mainapp/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings


class User(AbstractUser):
    pass

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
    phone = models.CharField(max_length=13,blank=True)
    wokrplace = models.CharField(max_length=50)

    def __str__(self):
        return 'Профіль користувача {}'.format(self.user.username)

user/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Field
from component import *




STATES = (
    ('', 'Choose...'),
    ('MG', 'Minas Gerais'),
    ('SP', 'Sao Paulo'),
    ('RJ', 'Rio de Janeiro')
)

# Реєстраційна форма
class RegistartionForm(forms.Form):
    email =  forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput())
    address_1 = forms.CharField(
        label='Address',
        widget=forms.TextInput(attrs={'placeholder': '1234 Main St'})
    )
    address_2 = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Apartment, studio, or floor'})
    )
    city = forms.CharField()
    state = forms.ChoiceField(choices=STATES)
    zip_code = forms.CharField(label='Zip')
    check_me_out = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column(InputLeftLabel('email'), css_class='col-md-6 mb-0'),
                Column(InputLeftLabel('password'), css_class='col-md-6 mb-0'),
                css_class='form-row'
            ),
            InputLeftLabel('address_1'),
            InputLeftLabel('address_2'),
            Row(
                Column('city', css_class='form-group col-md-6 mb-0'),
                Column('state', css_class='form-group col-md-4 mb-0'),
                Column('zip_code', css_class='form-group col-md-2 mb-0'),
                css_class='form-row'
            ),
            'check_me_out',
            Submit('submit', 'Sign in')
        )

mainapp/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response

class TestApiView(APIView):
    def get(self, request, *args, **kwargs):
        data = [{'id':1, 'name':'Джон'},{'id':2, 'name':'fill'} ]
        return Response(data)

mainapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render (request, 'index.html', {})

user/views.py
import os
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import  HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from user.models import *
from django.conf import settings

from user.forms import *



def index(request):
    # return render(request, 'index.html', {})
    return render(request, "user/index.html", {
        "form": RegistartionForm(),
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            if len(Profile.objects.filter(user=request.user.id)) != 0:
                profile = Profile.objects.get( user=request.user.id)
                request.session["photoUser"] = os.path.join("..",settings.MEDIA_URL,  profile.photo.url)
            return HttpResponseRedirect(reverse("user:index"))
        else:
            return render(request, "user/login.html", {
                "message": "Некорректний логін або пароль. Виправте та спробуйте знову."
            })
    else:
        return render(request, "user/login.html")

def login_view_redirect(request, next):
    return HttpResponseRedirect(reverse("user:index"))  

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("user:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "user/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "user/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("user:index"))
    else:
        return render(request, "user/register.html")

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Харчування ЗСУ{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">      <link href="{% static 'styles.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  </head>
  <body>
    <body >
        <!--wrapper-->
      <div class="wrapper toggled">
        <!--start header -->
        <header>
            <div class="topbar ">

            <nav class="navbar sticky-top navbar-light shadow rounded">
              <div class ="d-inline-flex">
                <a class="nav-link" href="{% url 'user:index' %}">
                  <img src="../static/favicon.png" class="rounded-circle border border-3 img-thumbnail small-picture" alt="nopic">
                </a>
              </div>

            <div class="nav-item ">
             {% if user.is_authenticated %}
            <div class ="d-inline-flex">
              <a class="nav-link" href="{% url 'user:index' %}">
              {% if request.session.photoUser %}
                <img src={{ request.session.photoUser }} class="small-picture rounded border border-1 img-thumbnail" alt="nopic">
              {% else %}
                <img src="../static/no_user_photo.png" class="small-picture rounded border border-1 img-thumbnail "  alt="nopic">
              {% endif %}
            </a>
                <div><small>Увійшли як <strong>{{ user.username }}</strong></small>.
                  <a class="nav-link" href="{% url 'user:logout' %}">вийти</a>
                </div>
                </div>
            {% else %}                      
                <div as="button" class="nav-link" href="{% url 'user:login' %}">Увійти</div>
            {% endif %}
            </div>
            </nav>

        </div>
        </header>
        <!--end header -->
        <!--start page wrapper -->
        <div class="page-wrapper ">
          <div class="container">
            {% if messages %}
          <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
            {% block content %}

            {% endblock %}

          </div>
        </div>
        <!--end page wrapper -->
        <footer class="page-footer">
			<p class="mb-0">Copyright © 2021. All right reserved.</p>
		</footer>
    </body>
    </body>
</html>

templates/components/input_field_finish_label.html
{% load crispy_forms_field %}

<div class="input-group input-group-sm mb-3">
    <div class="input-group-append">
        <span class="input-group-text"  for="{{ field.id_for_label }}">{{ field.label }}</span>
    </div>
    {% crispy_field field 'class' 'form-control' %}
</div>

templates/components/input_field_start_label.html
{% load crispy_forms_field %}

<div class="input-group input-group-sm mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text"  for="{{ field.id_for_label }}">{{ field.label }}</span>
    </div>
    {% crispy_field field 'class' 'form-control' %}
</div>

user/templates/user/index.html
{% extends "user/layout.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div>
    {% if user.is_authenticated %}
    {% if request.session.photoUser %}
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <div><img
            src="{{  request.session.photoUser }}"
            class="big-picture rounded border border-1 img-thumbnail"
            alt="nopic"
          /> </div>
          <button type="button" class="btn btn-primary full-width" >редагувати профіль</button>        
        </div>
        <div class="col">
          {% crispy form %}

            <ul class="list-group">

                <li class="list-group-item"><strong>Прізвище :</strong>{{user.first_name}}</li>
                <li class="list-group-item"><strong>Ім’я :</strong>{{user.last_name}}</li>
                <li class="list-group-item"><strong>Електронна адреса :</strong>{{user.email}}</li>
              </ul>
          </div>
    </div>
    
    {% else %}
    <img
      src="../static/no_user_photo.png"
      class="big-picture rounded border border-1 img-thumbnail"
      alt="nopic"
    />
    {% endif %}
    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Вийти</a>
                    </li> -->
    {% else %}
    <ul class="nav">

    <li class="nav-item">
      <a class="nav-link" href="{% url 'user:login' %}">Увійти</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'user:register' %}">Зареєструватись</a>
    </li>
</ul>

    {% endif %}
</div>
<hr />
{% endblock %}

user/templates/user/layout.html
{% extends "base.html" %}

{% block content %}
        <div>
            {% if user.is_authenticated %}
                Привіт <strong>{{ user.username }}</strong>.
            {% else %}
                Для подальшої роботи треба увійти у свій обліковий запис.
            {% endif %}
        </div>
        <hr>
        {% block body %}
        {% endblock %}
{% endblock %}

user/templates/user/login.html
{% extends "user/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'user:register' %}">Register here.</a>

{% endblock %}

user/templates/user/register.html
{% extends "user/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'user:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'user:login' %}">Log In here.</a>

{% endblock %}